# config.yaml
prowjob_namespace: default
pod_namespace: test-pods

plank:
  default_decoration_config:
    utility_images:
      clonerefs: "gcr.io/k8s-prow/clonerefs:v20200423-af610499d"
      initupload: "gcr.io/k8s-prow/initupload:v20200423-af610499d"
      entrypoint: "gcr.io/k8s-prow/entrypoint:v20200423-af610499d"
      sidecar: "gcr.io/k8s-prow/sidecar:v20200423-af610499d"
    gcs_configuration:
      bucket: bashfire-prow
      path_strategy: explicit
    gcs_credentials_secret: gcs-credentials

github_reporter:
  job_types_to_report:
  - presubmit
  - postsubmit

branch-protection:
  orgs:
    bashfire:
      protect: true

tide:
  sync_period: 1m
  queries:
  - orgs:
    - bashfire
    labels:
    - lgtm
    missingLabels:
    - do-not-merge/hold
    - do-not-merge/work-in-progress
