# config.yaml
prowjob_namespace: default
pod_namespace: test-pods

plank:
  job_url_template: 'https://prow.bashfire.dev/view/gcs/kubernetes-jenkins/{{if eq .Spec.Type "presubmit"}}pr-logs/pull{{else if eq .Spec.Type "batch"}}pr-logs/pull{{else}}logs{{end}}{{if .Spec.Refs}}{{if ne .Spec.Refs.Org ""}}/{{.Spec.Refs.Org}}_{{.Spec.Refs.Repo}}{{end}}{{end}}{{if eq .Spec.Type "presubmit"}}/{{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}{{else if eq .Spec.Type "batch"}}/batch{{end}}/{{.Spec.Job}}/{{.Status.BuildID}}/'
  report_templates:
    '*': '[Full PR test history](https://prow.bashfire.dev/pr-history?org={{.Spec.Refs.Org}}&repo={{.Spec.Refs.Repo}}&pr={{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3A{{with index .Spec.Refs.Pulls 0}}{{.Author}}{{end}}).'
  job_url_prefix_config:
    '*': https://prow.bashfire.dev/view/gcs/
  pod_pending_timeout: 15m
  pod_unscheduled_timeout: 1m
  default_decoration_configs:
    '*':
      timeout: 2h
      grace_period: 15s
      utility_images:
        clonerefs: "gcr.io/k8s-prow/clonerefs:v20200423-af610499d"
        initupload: "gcr.io/k8s-prow/initupload:v20200423-af610499d"
        entrypoint: "gcr.io/k8s-prow/entrypoint:v20200423-af610499d"
        sidecar: "gcr.io/k8s-prow/sidecar:v20200423-af610499d"
      gcs_configuration:
        bucket: bashfire-prow
        path_strategy: explicit
      # spiffxp-gke-dev-prow@spiffxp-gke-dev.iam.gserviceaccount.com
      gcs_credentials_secret: gcs-credentials # in test-pods namespace

sinker:
  resync_period: 1m
  max_prowjob_age: 12h
  max_pod_age: 12h
  terminated_pod_ttl: 30m

github_reporter:
  job_types_to_report:
  - presubmit
  - postsubmit

branch-protection:
  orgs:
    bashfire:
      protect: true

tide:
  sync_period: 1m
  queries:
  - orgs:
    - bashfire
    labels:
    - lgtm
    missingLabels:
    - do-not-merge/hold
    - do-not-merge/work-in-progress
  pr_status_base_urls:
    '*': https://prow.bashfire.dev/pr

deck:
  spyglass:
    size_limit: 200000000 # 200MB
    lenses:
    - lens:
        name: metadata
      required_files:
      - started.json|finished.json
      optional_files:
      - podinfo.json
    - lens:
        name: buildlog
      required_files:
        - build-log.txt
    - lens:
        name: junit
      required_files:
        - artifacts/junit.*\.xml
    - lens:
        name: coverage
      required_files:
        - artifacts/filtered.cov
      optional_files:
        - artifacts/filtered.html
    - lens:
        name: podinfo
      required_files:
        - podinfo.json
  tide_update_period: 1s
  rerun_auth_configs:
    '*':
      github_users:
      - spiffxp

presubmits:
  bashfire/prow-config:
  - name: test-build-cluster-presubmit
    cluster: prow-build-test
    decorate: true
    always_run: true
    skip_report: false
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
  - name: test-service-cluster-presubmit
    cluster: service-cluster
    decorate: true
    always_run: true
    skip_report: false
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
  - name: test-no-cluster-presubmit
    decorate: true
    always_run: true
    skip_report: false
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
