# plugins.yaml

# plugin-specific config

# config-updater
# update prow cluster's configmaps from the repo with this plugin enabled; assumed to be a single repo
config_updater:
  maps:
    config/prow/config.yaml:
      name: config
    config/prow/plugins.yaml:
      name: plugins
    config/jobs/**/*.yaml:
      name: job-config

# which plugins should be enabled for which orgs or org/repos
plugins:
  bashfire:
  # - approve
  - assign
  - cat
  - dog
  - hold
  - label
  - lgtm
  # - owners-label
  - pony
  - shrug
  - size
  - skip
  - trigger
  - wip
  # - verify-owners
  - yuks

  bashfire/prow-config:
  - config-updater
