# The 'gce-ssd-retain' storage class provisions a pd-ssd from GCE and
# specifies the 'Retain' reclaim policy.
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  namespace: default
  name: gce-ssd-retain
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
reclaimPolicy: Retain
