apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: "ks8-gsm-tools"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "ks8-gsm-tools"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: "ks8-gsm-tools"
subjects:
- kind: ServiceAccount
  namespace: default
  name: "ks8-gsm-tools"
roleRef:
 kind: ClusterRole
 name: "ks8-gsm-tools"
 apiGroup: rbac.authorization.k8s.io