apiVersion: v1
kind: Service
metadata:
  name: tide
  namespace: default
spec:
  clusterIP: 10.63.241.252
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30490
    port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    app: tide
  sessionAffinity: None
  type: NodePort
