presubmits:
  bashfire/prow-config:
  - name: pull-prow-config-checkconfig
    cluster: k8s-infra-prow-build
    decorate: true
    run_if_changed: '^(config/prow/(config|plugins).yaml$|config/jobs/.*.yaml$)'
    optional: true
    spec:
      containers:
      - image: gcr.io/k8s-prow/checkconfig:v20200423-af610499d
        command:
        - /checkconfig
        args:
        - --config-path=config/prow/config.yaml
        - --plugin-config=config/prow/plugins.yaml
        - --strict
        - --warnings=mismatched-tide-lenient
        - --warnings=tide-strict-branch
        - --warnings=needs-ok-to-test
        - --warnings=validate-owners
        - --warnings=missing-trigger
        - --warnings=validate-urls
        - --warnings=unknown-fields

periodics:
- interval: 10m
  name: echo-test
  cluster: k8s-infra-prow-build
  decorate: true
  spec:
    containers:
    - image: alpine
      command: ["/bin/date"]

postsubmits:
  bashfire/prow-config:
  - name: post-prow-config
    cluster: k8s-infra-prow-build
    decorate: true
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
