presubmits:
  bashfire/prow-config:
  - name: test-presubmit2
    decorate: true
    always_run: true
    skip_report: false
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
