presubmits:
  bashfire/prow-config:
  - name: pull-prow-config-checkconfig
    decorate: true
    run_if_changed: '^(config/prow/(config|plugins).yaml$|config/jobs/.*.yaml$)'
    optional: true
    spec:
      containers:
      - image: gcr.io/k8s-prow/checkconfig:v20200423-af610499d
        command:
        - /checkconfig
        args:
        - --config-path=config/prow/config.yaml
        - --plugin-config=config/prow/plugins.yaml
        - --strict

  - name: test-presubmit
    decorate: true
    always_run: true
    skip_report: false
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]

periodics:
- interval: 10m
  name: echo-test
  decorate: true
  spec:
    containers:
    - image: alpine
      command: ["/bin/date"]

postsubmits:
  bashfire/prow-config:
  - name: test-postsubmit
    decorate: true
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
