apiVersion: v1
kind: Service
metadata:
  name: hook
  namespace: default
spec:
  clusterIP: 10.63.246.52
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31896
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: hook
  sessionAffinity: None
  type: NodePort
